### ISSUE TITLE
Incompatibility with ansible.netcommon >=5.0.0

### ISSUE THREAD

**Issue by zjpeterson** [redhat-cop/network.base#33]
Any action using the task file `roles/resource_manager/includes/edit_resource.yaml`

Produces an error:
```
Unexpected failure during module execution: No module named 'ansible_collections.ansible.netcommon.plugins.module_utils.network.common.network_template'
```

This module util was removed in `ansible.netcommon` 5.0.0, yet the `galaxy.yml` for this collection specifies:
```
dependencies:
  "ansible.netcommon": ">=4.1.0"
```

There is no maximum compatible version specified, so  anyone not explicitly controlling their version of `ansible.netcommon` can experience this error.

**Comment by NilashishC** [comment]
@zjpeterson I believe this has been fixed now. This was most likely a side effect of one of the platform collections not replacing the deprecated import path for network_template with the update one.

**Comment by roverflow** [comment]
@zjpeterson Will be closing this ticket as it has been fixed, if the issue persists please feel free to reopen the ticket
