### ISSUE TITLE
Loop variable overlap

### ISSUE THREAD

**Issue by zjpeterson** [redhat-cop/network.base#34]
Ansible produces warnings like the following:
```
[WARNING]: TASK: network.base.resource_manager : Include configure task: The
loop variable 'item' is already in use. You should set the `loop_var` value in
the `loop_control` option for the task to something else to avoid variable
collisions and unexpected behavior.
```

When the following loop tasks execute:
https://github.com/redhat-cop/network.base/blob/4b4063c4e3646d12b61483e035e2d82974911620/roles/resource_manager/tasks/remediate.yaml#L20-L24

https://github.com/redhat-cop/network.base/blob/4b4063c4e3646d12b61483e035e2d82974911620/roles/resource_manager/includes/deploy.yaml#L15-L19

These loops, or the outer loop, should have a unique `loop_var` applied.

**Comment by NilashishC** [comment]
On the same note, the following warning is also shown from `/resource_manager/includes/edit_resource.yaml`:

```
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ module_vars[resource] }}
```

**Comment by rohitthakur2590** [comment]
@zjpeterson  Thanks for reporting this, this has been fixed and will be part of upcoming release.
