### ISSUE TITLE
LLDP_global modules has no overridden stare.

### ISSUE THREAD

**Issue by Roiki11** [redhat-cop/network.base#46]
##### SUMMARY
lldp_global has no state "overridden". Thus when running action: remediate the task fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
[remediate.yml](https://github.com/redhat-cop/network.base/blob/main/roles/resource_manager/tasks/remediate.yaml#L17-L20)
Cisco.ios.ios_lldp_global 

##### STEPS TO REPRODUCE
Use action: persist to pull lldp_global configuration or create it. Run with action: remediate. The playbook sets state to overridden [here](https://github.com/redhat-cop/network.base/blob/2cb242dd4c95db4a18f44c20f174097aec810fcc/roles/resource_manager/tasks/remediate.yaml#L17-L20). This is invalid for lldp_global task and the task fails. Playbook execution continues but the lldp state is not touched.

**Comment by rohitthakur2590** [comment]
@Roiki11  Thanks for reporting this, this is something which will be fixed with in cisco ios collections and be available in upcoming release for cisco ios collections.
