### ISSUE TITLE
Detect Drift returns incorrect results for devices which support onbox diff

### ISSUE THREAD

**Issue by rohitthakur2590** [redhat-cop/network.base#60]
ansib

##### SUMMARY

current detect drift  logic is based on checking if commands are generated, but this doesn't work for devices like Junos, 
which simply generates the commands and then depends on the ob-box diff to detect idempotency. 
##### ISSUE TYPE
- Bug Report

**Comment by roverflow** [comment]
Closing as pr fixing it has been merged
